export const JUZ_AMMA = [
  { id: 78, name: "النبأ", ayahCount: 40, order: 1 },
  { id: 79, name: "النازعات", ayahCount: 46, order: 2 },
  { id: 80, name: "عبس", ayahCount: 42, order: 3 },
  { id: 81, name: "التكوير", ayahCount: 29, order: 4 },
  { id: 82, name: "الانفطار", ayahCount: 19, order: 5 },
  { id: 83, name: "المطففين", ayahCount: 36, order: 6 },
  { id: 84, name: "الانشقاق", ayahCount: 25, order: 7 },
  { id: 85, name: "البروج", ayahCount: 22, order: 8 },
  { id: 86, name: "الطارق", ayahCount: 17, order: 9 },
  { id: 87, name: "الأعلى", ayahCount: 19, order: 10 },
  { id: 88, name: "الغاشية", ayahCount: 26, order: 11 },
  { id: 89, name: "الفجر", ayahCount: 30, order: 12 },
  { id: 90, name: "البلد", ayahCount: 20, order: 13 },
  { id: 91, name: "الشمس", ayahCount: 15, order: 14 },
  { id: 92, name: "الليل", ayahCount: 21, order: 15 },
  { id: 93, name: "الضحى", ayahCount: 11, order: 16 },
  { id: 94, name: "الشرح", ayahCount: 8, order: 17 },
  { id: 95, name: "التين", ayahCount: 8, order: 18 },
  { id: 96, name: "العلق", ayahCount: 19, order: 19 },
  { id: 97, name: "القدر", ayahCount: 5, order: 20 },
  { id: 98, name: "البينة", ayahCount: 8, order: 21 },
  { id: 99, name: "الزلزلة", ayahCount: 8, order: 22 },
  { id: 100, name: "العاديات", ayahCount: 11, order: 23 },
  { id: 101, name: "القارعة", ayahCount: 11, order: 24 },
  { id: 102, name: "التكاثر", ayahCount: 8, order: 25 },
  { id: 103, name: "العصر", ayahCount: 3, order: 26 },
  { id: 104, name: "الهمزة", ayahCount: 9, order: 27 },
  { id: 105, name: "الفيل", ayahCount: 5, order: 28 },
  { id: 106, name: "قريش", ayahCount: 4, order: 29 },
  { id: 107, name: "الماعون", ayahCount: 7, order: 30 },
  { id: 108, name: "الكوثر", ayahCount: 3, order: 31 },
  { id: 109, name: "الكافرون", ayahCount: 6, order: 32 },
  { id: 110, name: "النصر", ayahCount: 3, order: 33 },
  { id: 111, name: "المسد", ayahCount: 5, order: 34 },
  { id: 112, name: "الإخلاص", ayahCount: 4, order: 35 },
  { id: 113, name: "الفلق", ayahCount: 5, order: 36 },
  { id: 114, name: "الناس", ayahCount: 6, order: 37 },
];

export const TOTAL_JUZ_AMMA_AYAHS = 564;
export const TOTAL_JUZ_AMMA_SURAHS = 37;
